DEV-490 - capacitor lib updates
scbd/cbd-events pull request #5
Opened 2024-09-18 19:27 UTC by randyhoulahan

very late PR.   before cop the app store rejected and Christine got it in fast through a friend.  I had covid and never PR'ed it.

2024-09-18 19:28 UTC, rqk2k approved these changes

2024-09-18 19:40 UTC, blaisefonseca commented on components/article.vue
> +    console.log('this.blob',this.blob)
```suggestion
```

2024-09-18 20:12 UTC, sbilodeau requested changes

2024-09-18 20:12 UTC, sbilodeau commented on components/Calender/src/components/index.vue
> +  const end   = endDateTime.toISO({includeOffset:false})
this option is to remove the offet indicator of ta date. 

I think it's an incorrect way that either fix/cause the entries that disapear on edge case (begining/end of week entries) we experience it in Nairobi that was ok in montreal `UTC-5` vs `UTC+2`. Clealy a timezone issue that the application does not seems to handle 

```javascript
{includeOffset:false}
```

2024-09-18 20:12 UTC, sbilodeau commented on components/Calender/src/components/index.vue
> +    const   dayStartText     = dayStart.toISODate({includeOffset:false})
same as above

2024-09-18 20:13 UTC, sbilodeau commented
the PR is large and mixing multiple features in one PR.
- upgrade of library
- fix of date edgecase
- article stuff
- etc
it very important to try to make mutiple PRs. one for each feature.

2024-10-04 20:05 UTC, blaisefonseca commented
@rqk2k I think you should create a separate PR for your changes. this is mixing two things

2024-10-09 00:13 UTC, closed without merging